### ISSUE TITLE
CoP leads Agenda

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/communities-of-practice#9]
### Overview
This issue tracks the agenda for our weekly meetings

#### Issue Template
```
## [Date ]  Meeting Agenda

### Prework to prep for meeting
- [ ] #

### Recurring items: Happens on the ________ meeting
 - [ ] review any issues that are in the [new issue approval column]
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] [Name of Person]
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] 
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
-

### Notes from Meeting

### Task Items
```

### Links to other agenda issues for your team 
(so that you can easily post on their agendas items that come up at yours)

**Comment by ExperimentsInHonesty** [comment]
## 2022-05-04 Meeting Agenda

### Prework to prep for meeting
- [ ] #

### Recurring items: Happens on the ________ meeting
 - [ ] review any issues that are in the [new issue approval column]
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] [Name of Person]
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] 
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
-

### Notes from Meeting

### Task Items

**Comment by ExperimentsInHonesty** [comment]
[meeting_saved_chat.txt](https://github.com/hackforla/communities-of-practice/files/8628368/meeting_saved_chat.txt)

**Comment by ExperimentsInHonesty** [comment]
##  2022-11-12 Meeting Agenda

### Prework to prep for meeting
- [ ] #

### Recurring items: Happens on the ________ meeting
 - [ ] review any issues that are in the [new issue approval column]
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] [Name of Person]
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] 
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
- We are going to invite you to all the onboarding meetings for the year, please go into each one and add to your calendar.

### Notes from Meeting

### Task Items

**Comment by bradyse** [comment]
## 2023-01-04 Meeting Agenda

### Prework to prep for meeting
- [ ] #

### Recurring items: Happens on the ________ meeting
 - [ ] review any issues that are in the [new issue approval column]
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] [Name of Person]
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] Discuss audience interaction tool for guest speakers (UI/UX CoP needs a Q&A tool)
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
-

### Notes from Meeting

### Task Items

**Comment by mxajPrice** [comment]
## 2023 April 5 - CoP Leads meeting

### AGENDA
_Timezones listed as PDT._

- [ ] 17:00 _10 min_ 
- [ ] 17:20 _10 min_ 


### Notes:


> Attendees:

> [Data Science](https://github.com/hackforla/data-science)
> - [ ] 

> [Engineering](https://github.com/hackforla/engineering)
> - [ ] aj price
> - [ ] Alejandro Gomez
> - [ ] Harrison Katz
> - [ ] Micah Elm

> [Marketing](https://github.com/hackforla/marketing)


> [Ops](https://github.com/hackforla/ops)


> [Product Management](https://github.com/hackforla/product-management)


> [Revenue](https://github.com/hackforla/revenue)


> [UI/UX](https://github.com/hackforla/UI-UX)

**Comment by mxajPrice** [comment]
## 2023 May 3 - CoP Leads meeting

### AGENDA
_Timezones listed as PDT._

- [ ] 17:00 _ 15 min_ Follow up: What SDGs does each CoP fall under?
- [ ] 17:15 



### Notes:


### Action Items:


> Attendees:

> [Data Science](https://github.com/hackforla/data-science)
> - [x] Sophia Alice
> - [x] Karina Lopez

> [Engineering](https://github.com/hackforla/engineering)
> - [x] aj price
> - [ ] Alejandro Gomez
> - [x] Harrison Katz
> - [x] Micah Elm

> [Marketing](https://github.com/hackforla/marketing)

> [Ops](https://github.com/hackforla/ops)
> - [x] Jason Ebueng
> - [x] Dean Church

> [Product Management](https://github.com/hackforla/product-management)
> - [x] Bonnie Wolfe

> [Revenue](https://github.com/hackforla/revenue)

> [UI/UX](https://github.com/hackforla/UI-UX)
> - [x] Aparna Gopal
> - [x] Jennifer Nguyen

**Comment by mxajPrice** [comment]
## 2023 June 7 - CoP Leads meeting

### AGENDA
_Timezones listed as PDT._

- [ ] 17:00 _20 min_ Announcements
- [ ] 17:20 _20 min_ MK Docs walk-through - @ExperimentsInHonesty 
- [ ] 17:40 _10 min_ AOB


### Notes:
- Announcements:
   - We have officially sent our request to separate from Code for America
   - We are entering our 2nd Decade
   - We are partnering with GitHub to share Zoom expenses
- Will be adding CoP lead into to website
- Want to start including finished projects in wikis, may take some serious digging
- Can show progress on SDG 4.4 by showing volunteers moving through the skills matrix during their time with us


### Action Items:
- [ ] Bonnie to give team a walk-through of MK Docs in next meeting

> Attendees:

> [Data Science](https://github.com/hackforla/data-science)
> - [x] Sophia Alice
> - [x] Karina Lopez

> [Engineering](https://github.com/hackforla/engineering)
> - [x] aj price
> - [x] Alejandro Gomez
> - [x] Harrison Katz
> - [x] Micah Elm

> [Marketing](https://github.com/hackforla/marketing)

> [Ops](https://github.com/hackforla/ops)
> - [x] Jason Ebueng
> - [x] Dean Church

> [Product Management](https://github.com/hackforla/product-management)
> - [x] Bonnie Wolfe

> [Revenue](https://github.com/hackforla/revenue)

> [UI/UX](https://github.com/hackforla/UI-UX)
> - [x] Aparna Gopal
> - [x] Jennifer Nguyen
> - [ ] Julia Gab

**Comment by mxajPrice** [comment]
## 2023 July 5 - CoP Leads meeting

### AGENDA
_Timezones listed as PDT._

- [ ] 17:00 _05 min_ Welcome
   - Please rename yourself to NAME | CoP
- [ ] 17:20 _30 min_ Code of Conduct 
   - Incident review
   - Questions and feedback
- [ ] 17:40 _10 min_ [How did month 1 of Engineering CoP go](https://docs.google.com/presentation/d/16Pv007uOkQ09s2IZVde3dMGTKV5h7FOTZCeN6S4B3h0/edit?usp=sharing)?
- [ ] 17:50 _5 min_ AOB


### Notes:
- @agosmou -  New Relic is [awarding Grants](https://newrelic.com/about/impact-fund) right now.  Due date is 23 June.

### Action Items:


> Attendees:

> [Data Science](https://github.com/hackforla/data-science)
> - [x] Sophia Alice
> - [ ] Karina Lopez
> - [x] Abe Khaleghi

> [Engineering](https://github.com/hackforla/engineering)
> - [x] aj price
> - [x] Alejandro Gomez
> - [x] Harrison Katz
> - [x] Micah Elm

> [Marketing](https://github.com/hackforla/marketing)

> [Ops](https://github.com/hackforla/ops)
> - [x] Jason Ebueng
> - [x] Chelsey Beck
> - [ ] Dean Church

> [Product Management](https://github.com/hackforla/product-management)
> - [x] Bonnie Wolfe

> [Revenue](https://github.com/hackforla/revenue)

> [UI/UX](https://github.com/hackforla/UI-UX)
> - [x] Aparna Gopal
> - [x] Jennifer Nguyen
> - [x] Julia Gab

**Comment by ExperimentsInHonesty** [comment]
@agosmou I have written to the person who posted on linked, can you keep an eye out for the response https://www.linkedin.com/feed/update/urn:li:activity:7071542652340473856?commentUrn=urn%3Ali%3Acomment%3A%28activity%3A7071542652340473856%2C7075886574311280640%29&dashCommentUrn=urn%3Ali%3Afsd_comment%3A%287075886574311280640%2Curn%3Ali%3Aactivity%3A7071542652340473856%29

**Comment by ExperimentsInHonesty** [comment]
### Milestones
01 Compliance
02 Security
03 Project Management
04 Team Workflow
05.01 HfLA MVP knowledge
05.02 HfLA All teams do
05.03 HfLA Some teams do
05.04. HfLA We Must Do in future
05.05 HfLA We Should Do in future
05.06 HfLA We Could Do in future
05.07 HfLA We Won't Do in future unless something changes
Lightning Talks
Speaker
Mentor Night
Open Networking

**Comment by mxajPrice** [comment]
## 2023 August 2 - CoP Leads meeting

### AGENDA
_Timezones listed as PDT._

- [ ] 17:00 _05 min_ - Welcome
   - Please rename yourself to NAME | CoP
- [ ] 17:05 _10 min_ - Updates to meeting times on [CoP repo](https://github.com/hackforla/communities-of-practice#communities-of-practice)
- [ ] 17:15 _5 min_ - Engineering CoP updates
   - AJ leaving in one month
   - Other leads will need to be able '@' here and channel in Slack
- [ ] 17:20 _30 min_ - CoP check-in (How was last month?  What are your plans for August?)
   - 17:20 _6 min_ - Data Science
   - 17:26 _6 min_ - Engineering
   - 17:32 _6 min_ - Dev Ops
   - 17:38 _6 min_ - Product Management
   - 17:44 _6 min_ - UI/UX


### Questions:
- Can we get reminders when there are onboardings?  Would be nice to prep welcome messages.

### Notes:


### Action Items:


> Attendees:

> [Data Science](https://github.com/hackforla/data-science)
> - [x] Sophia Alice
> - [x] Karina Lopez
> - [x] Abe Khaleghi

> [Engineering](https://github.com/hackforla/engineering)
> - [x] aj price
> - [x] Alejandro Gomez
> - [x] Harrison Katz
> - [x] Micah Elm

> [Marketing](https://github.com/hackforla/marketing)

> [Ops](https://github.com/hackforla/ops)
> - [x] Jason Ebueng
> - [ ] Chelsey Beck
> - [x] Dean Church

> [Product Management](https://github.com/hackforla/product-management)
> - [x] Bonnie Wolfe

> [Revenue](https://github.com/hackforla/revenue)

> [UI/UX](https://github.com/hackforla/UI-UX)
> - [x] Aparna Gopal
> - [x] Jennifer Nguyen
> - [x] Julia Gab

**Comment by luca-navarrete** [comment]
Add to the next agenda: 
```
- [ ] Review with Bonnie 
  - [ ] Slack channels (active/dormant/archived)
  - [ ] Slack channel pins and bookmarks
```

**Comment by ExperimentsInHonesty** [comment]
## 2024-03-06 Meeting Agenda

### Prework to prep for meeting
- [ ] #

### Recurring items: Happens on the ________ meeting
 - [ ] review any issues that are in the [new issue approval column]
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] [Name of Person]
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] 
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
-

### Notes from Meeting
- Chelsey | DevOps
  - creating IAM resources using terraform and working on wiki for member onboarding
  - Srihari chellu will be the Devops Project Manager
- Aparna | UI/UX Community of Practice 
  - reorganized our their planning meeting to help them publish the upcoming events in advance https://github.com/hackforla/UI-UX/issues/553
  - Cleanup 

### Task Items

**Comment by rayneng** [comment]
## 2025-08-06  Meeting Agenda

### Prework to prep for meeting
- [ ] #

### Recurring items: Happens on the ________ meeting
 - [ ] review any issues that are in the [new issue approval column]
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] [Name of Person]
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs

### Notes from Meeting
- projects live in the marketplace require a lot more attention from the org than projects in development
  - TDM
  - Food Oasis
- projects that take longer to develop is not a problem. But as soon as it flips over to live...
  - needs high level of attention
  - needs Bonnie time
  - stands to hurt HfLA's organization
- really important that at time of launch, we have a plan for operation (that survive key volunteers leaving team)
  - need to look for service / resource deprecation (or increased pricing plan)
  - HfLA is not taking on full-time owners of projects to maintain


### Task Items

**Comment by RSkuma** [comment]
## [2025-09-03 ]  Meeting Agenda

### Prework to prep for meeting
- [ ] #

### Recurring items: Happens on the ________ meeting
- [x] review any issues that are in the [new issue approval column]
- [x] Review to see if there are any members to Onboard or Offboard 
  - [x]  Onboarded Elvin Kosova, adding him to 1password vault

### New Items
- [ ] Discussed organization updates

### FYIs
-

### Notes from Meeting
- Discussed ways to add automation to improve HFLA operations, 
- Onboarding/offboarding(adding to slack, github, 1password), lead onboarding/offboarding, ticket automation, 
- (Future Issue)How to track the activity/patterns of volunteers, particularly the ones who do not attend CoP meetings, but also tracking volunteers who join CoP but move to projects
- Would like clarity on Bonnie role transition, what are responsibilities and duties that others need to take over, and how would automation help this
### Task Items

**Comment by rayneng** [comment]
### 2025-10-01 Notes


Ideas on what to share between CoPs
- UI/UX CoP (Design, Research, Content/Writing)
  - Planning meeting 1xmonth
  - Week of general onboarding is the Community Meetup (bi-monthly)
  - Community Meetups: Following 5 topics covered: Portfolio Reviews - Resume Reviews - Design Feedback - Interview Technical Skills - Post - Onboarding Support
  - One week of the month - a main event is conducted - either Workshops/Guest Speakers etc. 
  - Upcoming schedule wiki: https://github.com/hackforla/UI-UX/wiki#upcoming-meetings-
  - Guest Speakers: https://github.com/hackforla/UI-UX/wiki/Guest-Speakers
    - harder to commit time to acquiring guest speakers
- DevOps & Eng
  - interest in speakers (if relevant to the CoP)
  - we could have key members give presentations on achievements / wins
    - highly dependent on that person's capacity, not guaranteed that all members are interested in doing this
    - design + research in-house speaker series, talk about success stories
- DataScience does speakers

Achievements Doc
- each quarter the leads (CoP _and_ Projects) will jot down the 4-5 biggest wins from the team

Bonnie's notes
  - achievements are particularly good for devops so we can see ppl's progress
  - uiux: would want to handpick the teams to do this
  - eng?
    - tdm calculator
    - hfla site

Elvin's prev exp
- demo day (every other week, end of sprint)
  - product led demo (not technical) + roadmap of what's coming next
- scrum of scrums

In the past
- each month different team had PM-led pres
  - we could have similar pres for eng
  - PM could help with "this is what our product is about"
  - eng focus for the rest of the slides
  - we have a template (PM focused, need to adapt to Eng)
  - TDM has dangerously insecure html >> purify(?) --> good presentation

We could do talks on Decision Records
- can be utilized for all practices
- see: https://www.hackforla.org/about/#platform

<details><summary>Example of Community Meetup Post</summary>
<p>

Community Meetup!
 We will be covering the following topics during the Community Meetup
- Portfolio Peer Reviews
- Resume Peer Reviews
- Interview Technical Skills Discussions
- Design Feedback
- Post - Onboarding Support

</p>
</details> 

Other questions
- https://docs.google.com/document/d/1gV4RuCW1wfE1mUw0LEZNrTzA-NXVKIDeGHQ_8Ddv9MI/edit?usp=meetingnotes&showmeetingnotespromo=true
  - where does this go?

### Action Items
- [ ] create Wiki page in this repo on How To Do XYZ in a CoP?
  - [ ] build up knowledge base on how to run CoPs
  - we can chip away at this at lead meetings
